// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ChicagoCodeCampCodeFirst.Context;
using System;

namespace ChicagoCodeCampCodeFirst.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan?>("ClassDuration");

                    b.Property<int?>("CourseNumber")
                        .IsRequired();

                    b.Property<int?>("DepartmentId")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<DateTimeOffset?>("EndDate");

                    b.Property<Guid?>("InstructorId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastChangedByUser")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("LastChangedTimestamp")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.CourseEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CourseId");

                    b.Property<decimal>("FinalGrade")
                        .HasColumnType("decimal(6,3)");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastChangedByUser")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("LastChangedTimestamp")
                        .IsRequired();

                    b.Property<Guid>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.Department", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastChangedByUser")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("LastChangedTimestamp")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired();

                    b.Property<int?>("DepartmentId")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<DateTime?>("HireDate")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastChangedByUser")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("LastChangedTimestamp")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired();

                    b.Property<int>("ExpectedGraduationYear");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Foo");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastChangedByUser")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("LastChangedTimestamp")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.Course", b =>
                {
                    b.HasOne("ChicagoCodeCampCodeFirst.Context.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChicagoCodeCampCodeFirst.Context.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId");
                });

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.CourseEnrollment", b =>
                {
                    b.HasOne("ChicagoCodeCampCodeFirst.Context.Course", "Course")
                        .WithMany("EnrolledStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChicagoCodeCampCodeFirst.Context.Student", "Student")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChicagoCodeCampCodeFirst.Context.Instructor", b =>
                {
                    b.HasOne("ChicagoCodeCampCodeFirst.Context.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
